export const CATEGORIES = {
  all: "Все",
  reclama: "Реклама",
  docReclama: "Документальная_реклама",
  korpVideo: "Корпоративное_видео",
  FPV: "FPV-съемка",
  graph: "Грфаика",
  docKino: "Документальное_кино",
  clip: "Клипы",
  showreel: "Шоурилы",
};

export const TAGS = {
  tv: "tv",
  olv: "olv",
  clv: "clv",
  CG: "CG",
  threeD: "3D",
  VFX: "VFX",
  NFT: "NFT",
  digital: "digital",
  hr: "HR-ролики",
  pres: "презентации",
  aero: "аэросъемка",
  extrim: "экстрим",
  show: "шоу",
  web: "веб-сериалы",
  almanah: "альманахи",
  snippet: "сниппеты",
  film: "фильмы",
  visit: "визитки",
  live: "лайвы",
  promo: "промо",
  explay: "эксплейнеры",
};
